GET {{local_api}}

###
GET {{local_api}}/articles

###
POST {{local_api}}/articles


### create board
POST {{local_api}}/board
Content-Type: application/json

{
  "boardName": "test board4"
}

### get board list
GET {{local_api}}/board

### create category
POST {{local_api}}/article/category
Content-Type: application/json

{
  "categoryName": "test category3"
}